# Generated by Django 3.1.2 on 2020-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('attendance', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Not Active', max_length=10)),
            ],
        ),
    ]
